exports.Presence = require('./Ready/Presence.Module.js')
exports.CryptoPrice = require('./Ready/CryptoPrice.Module.js')
exports.Trades = require('./Ready/Trades.Module.js')
exports.News = require('./Ready/News.Module.js')
exports.WhaleTrades = require('./Ready/WhaleTrades.Module.js')